#!/bin/bash -l
set -ex

ruby --version | grep 2\..\..

rails -v

for rubyversion in 2.4.5 2.5.3 2.6.0; do
	set +x;
	echo "+ rvm use $rubyversion"
	rvm use $rubyversion
	set -x
	ruby --version | grep $rubyversion
	rails -v
	echo 'puts "hello"' | ruby
done

